// ВНИМАНИЕ: файл генерируется автоматически.
// Перегенерировать: node --env-file=.env.local scripts/build-brand-map.mjs
//
// Карта «ключ бренда → каноничное отображаемое имя». Ключ — это brandKey()
// (lowercase без пробелов/пунктуации). Покрывает только бренды, у которых в БД
// встретилось несколько вариантов написания; остальные канонизируются эвристикой.
export const BRAND_MAP = {
  "aba": "ABA",
  "abs": "ABS",
  "acdelco": "ACDelco",
  "addaxq": "Addax-q",
  "aiko": "Aiko",
  "airline": "Airline",
  "aisin": "Aisin",
  "ajusa": "Ajusa",
  "akitaka": "Akitaka",
  "alkar": "Alkar",
  "all4motors": "All4Motors",
  "alliednippon": "Allied Nippon",
  "allring": "AllRing",
  "amiwa": "Amiwa",
  "anto": "Anto",
  "aplus": "APlus",
  "arirang": "Arirang",
  "ashika": "Ashika",
  "asmetal": "AS METAL",
  "aspaco": "Aspaco",
  "asva": "Asva",
  "atek": "Atek",
  "auger": "Auger",
  "autocomponent": "Autocomponent",
  "autofamily": "Autofamily",
  "autoprofi": "Autoprofi",
  "avers": "Avers",
  "avtos": "AvtoS",
  "avtostandart": "Avtostandart",
  "avtoworld": "Avto.World",
  "azumi": "Azumi",
  "betterbrakeparts": "Better Brake Parts",
  "bibicare": "BiBiCare",
  "bigfilter": "BIG Filter",
  "blitz": "Blitz",
  "blueprint": "BLUEPRINT",
  "borgwarner": "BORGWARNER",
  "borsehung": "Borsehung",
  "bosal": "Bosal",
  "bosch": "Bosch",
  "brave": "Brave",
  "brembo": "Brembo",
  "bremi": "Bremi",
  "brisk": "Brisk",
  "carberry": "Carberry",
  "cargen": "CarGen",
  "cargo": "Cargo",
  "carvilleracing": "Carville Racing",
  "changan": "Changan",
  "chrysler": "Chrysler",
  "clearlight": "ClearLight",
  "comline": "Comline",
  "contitech": "Contitech",
  "corteco": "Corteco",
  "cummins": "Cummins",
  "daewoo": "Daewoo",
  "daidometal": "Daido Metal",
  "dayco": "Dayco",
  "deko": "Deko",
  "delcoparts": "DELCOPARTS",
  "delphi": "Delphi",
  "deltaparts": "DELTAPARTS",
  "denso": "Denso",
  "depo": "Depo",
  "deppul": "DePPuL",
  "deqst": "Deqst",
  "detail": "Detail",
  "dokuro": "Dokuro",
  "dolz": "Dolz",
  "donaldson": "Donaldson",
  "element": "Element",
  "elring": "Elring",
  "elwisroyal": "Elwis Royal",
  "emmetec": "Emmetec",
  "eneos": "Eneos",
  "enterprise": "Enterprise",
  "euroricambi": "Euroricambi",
  "febest": "Febest",
  "febi": "Febi",
  "fenox": "Fenox",
  "ferodo": "Ferodo",
  "fersa": "Fersa",
  "fobos": "Fobos",
  "ford": "Ford",
  "formpart": "Formpart",
  "foton": "Foton",
  "freccia": "Freccia",
  "freez": "FREE-Z",
  "frenkit": "Frenkit",
  "gallant": "Gallant",
  "gates": "Gates",
  "gbrake": "G-brake",
  "geely": "Geely",
  "gelzer": "Gelzer",
  "genergy": "G-Energy",
  "gieffe": "Gieffe",
  "globelt": "Globelt",
  "glyco": "Glyco",
  "goetze": "Goetze",
  "goodwill": "GoodWill",
  "gpart": "G-part",
  "gparts": "GParts",
  "grass": "Grass",
  "greatwall": "Great Wall",
  "greencool": "GreenCool",
  "gsparts": "GSParts",
  "gud": "G.U.D",
  "hdparts": "HD-parts",
  "hengst": "Hengst",
  "hessa": "Hessa",
  "honda": "Honda",
  "hotparts": "Hot-parts",
  "hyundaikia": "Hyundai/Kia",
  "hyundaixteer": "HYUNDAI XTeer",
  "jaguar": "Jaguar",
  "japanparts": "Japanparts",
  "jpgroup": "JP Group",
  "jsasakashi": "JS Asakashi",
  "kacmazlar": "Kacmazlar",
  "kashiyama": "Kashiyama",
  "kentek": "Kentek",
  "kimiko": "Kimiko",
  "king": "King",
  "klakson": "Klakson",
  "knecht": "Knecht",
  "kolbenschmidt": "Kolbenschmidt",
  "kongsberg": "Kongsberg",
  "koyo": "Koyo",
  "krafttech": "KRAFTtech",
  "krauf": "Krauf",
  "kroner": "Kroner",
  "lada": "Lada",
  "landrover": "Land Rover",
  "lema": "Lema",
  "lemforder": "Lemforder",
  "lesjofors": "Lesjofors",
  "lifan": "Lifan",
  "liquimoly": "Liqui Moly",
  "luzar": "Luzar",
  "lykmc": "Lykmc",
  "lynxauto": "LYNXauto",
  "magnetimarelli": "Magneti Marelli",
  "mahle": "Mahle",
  "mando": "Mando",
  "mann": "Mann",
  "mannol": "Mannol",
  "mansons": "Mansons",
  "mapco": "Mapco",
  "marshall": "Marshall",
  "maruichi": "Maruichi",
  "masterkit": "MasterKit",
  "masuma": "Masuma",
  "mazda": "Mazda",
  "meatdoria": "Meat&Doria",
  "mecarm": "Mecarm",
  "mercedes": "Mercedes",
  "mercedesbenz": "MERCEDES-BENZ",
  "metalcaucho": "Metalcaucho",
  "metelli": "Metelli",
  "meyle": "Meyle",
  "micro": "Micro",
  "miles": "Miles",
  "mitsubishi": "Mitsubishi",
  "mobil": "Mobil",
  "mobiland": "Mobiland",
  "mobiletron": "Mobiletron",
  "monroe": "Monroe",
  "moog": "Moog",
  "motorcraft": "Motorcraft",
  "motorherz": "Motorherz",
  "motul": "Motul",
  "mousson": "Mousson",
  "msmarshal": "Ms-Marshal",
  "musashi": "Musashi",
  "narva": "Narva",
  "needful": "NeedFul",
  "nissan": "Nissan",
  "nissens": "Nissens",
  "nisshinbo": "Nisshinbo",
  "oem": "OEM",
  "oemgenuinegasket": "OEM Genuine Gasket",
  "ombra": "Ombra",
  "optimal": "Optimal",
  "osk": "O.S.K.",
  "osram": "Osram",
  "partsmall": "PARTS-MALL",
  "perfect": "Perfect",
  "philips": "Philips",
  "pilenga": "Pilenga",
  "polcar": "Polcar",
  "porsche": "Porsche",
  "poweredge": "PowerEdge",
  "powerstop": "Power Stop",
  "provia": "ProVia",
  "pullman": "Pullman",
  "quattrofreni": "Quattro Freni",
  "raon": "Raon",
  "rbexide": "Rb-exide",
  "reinwell": "ReinWell",
  "renault": "Renault",
  "rexant": "Rexant",
  "rezkon": "Rezkon",
  "riginal": "Riginal",
  "roadrunner": "RoadRunner",
  "rocky": "Rocky",
  "rosteco": "Rosteco",
  "rubena": "Rubena",
  "ruei": "Ruei",
  "saab": "Saab",
  "sachs": "Sachs",
  "sakura": "Sakura",
  "sangsin": "Sangsin",
  "sasic": "Sasic",
  "sbnagamochi": "SB Nagamochi",
  "scania": "Scania",
  "sem": "SE-M",
  "sensen": "SenSen",
  "setparts": "Set Parts",
  "sfengine": "SF Engine",
  "shacman": "Shacman",
  "sidem": "Sidem",
  "sk": "S&K",
  "speedmate": "SpeedMate",
  "ssangyong": "Ssangyong",
  "standardsprings": "Standard Springs",
  "starline": "StarLine",
  "stellox": "Stellox",
  "subaru": "Subaru",
  "suzuki": "Suzuki",
  "swag": "Swag",
  "taiho": "Taiho",
  "taksim": "Taksim",
  "tama": "Tama",
  "tatsumi": "Tatsumi",
  "tedgum": "TEDGUM",
  "teikin": "Teikin",
  "tenacity": "Tenacity",
  "tesla": "Tesla",
  "teslatechnics": "TeslaTechnics",
  "textar": "Textar",
  "thorvik": "Thorvik",
  "tiguar": "Ti-Guar",
  "timken": "Timken",
  "tokico": "Tokico",
  "tonghong": "TONG HONG",
  "totachi": "Totachi",
  "toyota": "Toyota",
  "trialli": "Trialli",
  "trusting": "Trusting",
  "ukorauto": "UkorAuto",
  "unitedmotors": "United Motors",
  "valeo": "Valeo",
  "valeophc": "Valeo PHC",
  "valvoline": "Valvoline",
  "victorreinz": "Victor Reinz",
  "vigor": "Vigor",
  "vika": "Vika",
  "volvo": "Volvo",
  "wolf": "Wolf",
  "x5resource": "X5 resource",
  "yada": "Yada",
  "yato": "Yato",
  "zepro": "Zepro",
  "zfrussia": "ZF Russia",
  "zimmermann": "Zimmermann",
  "zuvteil": "ZuvTeil",
  "автоброня": "Автоброня",
  "автодетальсервис": "Автодеталь-Сервис",
  "автокомпонент": "Автокомпонент",
  "автомагнат": "Автомагнат",
  "автоприбор": "Автоприбор",
  "балаково": "Балаково",
  "белак": "БелАК",
  "белзан": "БелЗАН",
  "белмаг": "БелМаг",
  "вектор": "Вектор",
  "волгопромтранс": "Волгопромтранс",
  "делотехники": "Дело Техники",
  "завгар": "ЗавГар",
  "костромскойфильтр": "Костромской фильтр",
  "лукойл": "Лукойл",
  "маяк": "Маяк",
  "одасервис": "ОДА Сервис",
  "пластик": "Пластик",
  "полиуретан": "Полиуретан",
  "россия": "Россия",
  "сэви": "Сэви",
  "технокам": "ТехноКам",
  "триал": "Триал",
  "турбоинжиниринг": "Турбо Инжиниринг",
  "унипсервис": "УНИП СЕРВИС"
};
